### PR TITLE
Hisham homework

### PR DESCRIPTION
**Pull request by Hishamhamed**
Hallo Ahmed i created a new file just for homework and i used this new branch

### CODE REVIEW

**Comment by AhmedBHameed** [comment]
Hello @Hishamhamed, this is the first homework, can you please complete the second homework to merge them both together ?
Thank you.

**Comment by AhmedBHameed** [comment]
Hello @Hishamhamed, This is only one homework. Can you solve the other one ? IF yes then i would love to see them in this pull request.

**Comment by Hishamhamed** [comment]
I will do that

**Comment by AhmedBHameed** [comment]
@Hishamhamed closed due old date.
Feel free correcting homework and solving other ones. then open new pull request.

**Pull request closed without merging**
